services:
  - type: web
    name: scrapper
    env: node
    plan: starter
    buildCommand: npm install && npm build
    startCommand: rsync -a public/ /data/public/ && yarn start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~18.16.0
      - key: NODE_ENV
        value: production
